export const STORE_LIST_REQUEST = 'STORE_LIST_REQUEST'
export const STORE_LIST_SUCCESS = 'STORE_LIST_SUCCESS'
export const STORE_LIST_FAIL = 'STORE_LIST_FAIL'

export const STORE_REGISTER_REQUEST = 'STORE_REGISTER_REQUEST'
export const STORE_REGISTER_SUCCESS = 'STORE_REGISTER_SUCCESS'
export const STORE_REGISTER_FAIL = 'STORE_REGISTER_FAIL'
export const STORE_LOGOUT = 'STORE_LOGOUT'

export const STORE_LOGIN_REQUEST = 'STORE_LOGIN_REQUEST'
export const STORE_LOGIN_SUCCESS = 'STORE_LOGIN_SUCCESS'
export const STORE_LOGIN_FAIL = 'STORE_LOGIN_FAIL'